version: 2.1

orbs:
  node: circleci/node@1.1


jobs:
  build-and-test:  
    docker:
      - image: cimg/node:12.4.0
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: node --version
      - run:
          name: Run tests
          command: npm run test

workflows:
  sample: 
    jobs:
      - build-and-test
